# docker pull openvidu/openvidu-server

# FROM docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-server-kms:2.21.0

# services:
#   openvidu-kms:
#     image: openvidu/openvidu-server-kms:2.14.0
#     restart: on-failure
#     ports:
#       - "4443:4443"
#     environment:
#       - DOMAIN_OR_PUBLIC_IP=${DOMAIN_OR_PUBLIC_IP}
#       - OPENVIDU_SECRET=${OPENVIDU_SECRET}